window.CYBER_QUIZ_QUESTIONS = [
  {
    id: "easy-ssh-name",
    difficulty: "easy",
    topic: "SSH",
    lesson: "8. Acesso remoto com SSH",
    source: "02-cloud-basics/08-communicating-with-cloud-computers-remotely-using-ssh/",
    question: "O que significa a sigla SSH?",
    choices: [
      "Secure Shell",
      "Simple Secure Host",
      "Server Software Handler",
      "Shared System Header",
    ],
    correct: 0,
    explanation:
      "SSH significa Secure Shell. O protocolo cria um canal criptografado entre cliente e servidor e normalmente usa TCP na porta 22.",
  },
  {
    id: "easy-http-port",
    difficulty: "easy",
    topic: "HTTP",
    lesson: "11. Apache, HTTP e exposição web",
    source: "03-phishing/11-file-hosting-and-firewall-settings/",
    question: "Qual é a porta padrão do HTTP?",
    choices: ["21", "22", "80", "443"],
    correct: 2,
    explanation:
      "HTTP usa TCP na porta 80 por padrão. HTTPS normalmente usa 443, SSH usa 22 e FTP usa 21.",
  },
  {
    id: "easy-ami",
    difficulty: "easy",
    topic: "AWS EC2",
    lesson: "7. Provisionando Kali Linux no EC2",
    source: "02-cloud-basics/07-installing-kali-linux-on-the-cloud/",
    question: "O que é uma AMI no Amazon EC2?",
    choices: [
      "Uma instância que já está executando",
      "Uma imagem usada como modelo para iniciar instâncias",
      "Uma regra de entrada do Security Group",
      "Um endereço IP público permanente",
    ],
    correct: 1,
    explanation:
      "AMI significa Amazon Machine Image. Ela reúne o sistema e as configurações usados como modelo para criar uma ou mais instâncias EC2.",
  },
  {
    id: "easy-mfa",
    difficulty: "easy",
    topic: "Autenticação",
    lesson: "6. Criando e protegendo uma conta AWS",
    source: "02-cloud-basics/06-signing-up-with-aws/",
    question: "Qual é a principal função do MFA?",
    choices: [
      "Aumentar a velocidade do login",
      "Exigir mais de um fator para confirmar a identidade",
      "Substituir todos os controles de autorização",
      "Monitorar os custos da conta",
    ],
    correct: 1,
    explanation:
      "MFA combina fatores diferentes, como uma senha e algo que a pessoa possui. Assim, uma senha exposta não basta, sozinha, para concluir o login.",
  },
  {
    id: "easy-linux-debian-kali",
    difficulty: "easy",
    topic: "Linux",
    lesson: "7. Provisionando Kali Linux no EC2",
    source: "02-cloud-basics/07-installing-kali-linux-on-the-cloud/",
    question: "Qual relação entre Linux, Debian e Kali Linux está correta?",
    choices: [
      "Kali é apenas outro nome para Debian",
      "Linux é uma distribuição baseada em Kali",
      "Linux é o kernel, Debian é uma distribuição e Kali deriva do Debian",
      "Debian é um pacote instalado dentro do Kali",
    ],
    correct: 2,
    explanation:
      "Linux é o kernel. Debian combina esse kernel com ferramentas e pacotes para formar uma distribuição; Kali é uma distribuição baseada no Debian e voltada a segurança.",
  },
  {
    id: "easy-phishing-definition",
    difficulty: "easy",
    topic: "Engenharia social",
    lesson: "10. Phishing e engenharia social",
    source: "03-phishing/10-introduction-to-phishing/",
    question: "O que define o phishing?",
    choices: [
      "Toda mensagem que contém malware",
      "Qualquer página visualmente malfeita",
      "Uma representação enganosa que tenta induzir uma ação",
      "Um ataque que sempre explora o navegador",
    ],
    correct: 2,
    explanation:
      "Phishing é engenharia social: uma mensagem ou interface se apresenta de forma enganosa para induzir a pessoa a clicar, responder, visitar ou aprovar algo. Não depende necessariamente de malware.",
  },
  {
    id: "easy-apache",
    difficulty: "easy",
    topic: "Servidor web",
    lesson: "11. Apache, HTTP e exposição web",
    source: "03-phishing/11-file-hosting-and-firewall-settings/",
    question: "Qual é a função do Apache HTTP Server no laboratório?",
    choices: [
      "Resolver nomes de domínio",
      "Receber requisições HTTP e servir recursos web",
      "Criar regras no Security Group",
      "Gerenciar as chaves privadas do SSH",
    ],
    correct: 1,
    explanation:
      "Apache é o processo servidor que escuta requisições HTTP, localiza recursos no document root e devolve respostas ao navegador.",
  },
  {
    id: "easy-ec2-name",
    difficulty: "easy",
    topic: "AWS EC2",
    lesson: "7. Provisionando Kali Linux no EC2",
    source: "02-cloud-basics/07-installing-kali-linux-on-the-cloud/",
    question: "O que significa EC2?",
    choices: [
      "Error Code 2",
      "Elastic Compute Cloud",
      "Electronic Command Control",
      "Enterprise Container Configuration",
    ],
    correct: 1,
    explanation:
      "EC2 significa Elastic Compute Cloud. É o serviço da AWS usado para provisionar e administrar capacidade computacional por meio de instâncias.",
  },
  {
    id: "easy-document-root",
    difficulty: "easy",
    topic: "Apache",
    lesson: "11. Apache, HTTP e exposição web",
    source: "03-phishing/11-file-hosting-and-firewall-settings/",
    question: "O que é o document root do Apache?",
    choices: [
      "O arquivo que guarda as regras do firewall",
      "O diretório dos logs de autenticação",
      "O diretório-base de onde o servidor publica arquivos",
      "A chave usada pelo certificado HTTPS",
    ],
    correct: 2,
    explanation:
      "O document root é o ponto inicial usado para localizar os arquivos publicados. No ambiente estudado, o caminho padrão é /var/www/html.",
  },
  {
    id: "easy-sftp",
    difficulty: "easy",
    topic: "SFTP",
    lesson: "12. Cópia de páginas e SFTP",
    source: "03-phishing/12-cloning-websites-and-uploading-them-to-the-cloud/",
    question: "Qual afirmação diferencia corretamente FTP de SFTP?",
    choices: [
      "FTP é criptografado e SFTP não é",
      "SFTP é um protocolo de transferência que usa a infraestrutura do SSH",
      "SFTP é apenas FTP executado em uma VPN",
      "Os dois são o mesmo protocolo e usam a porta 21",
    ],
    correct: 1,
    explanation:
      "SFTP é um protocolo próprio executado sobre a infraestrutura do SSH, normalmente na porta 22. Ele não é o FTP antigo simplesmente renomeado.",
  },
  {
    id: "medium-authorization",
    difficulty: "medium",
    topic: "Ética e escopo",
    lesson: "1. Visão geral do curso",
    source: "01-introduction-to-cloud-computing-for-hackers/01-teaser/",
    question: "Por que a autorização precisa definir ativos, período e ações permitidas antes de um teste?",
    choices: [
      "Para fazer as ferramentas executarem mais rápido",
      "Para separar o teste autorizado de ações fora do escopo",
      "Para eliminar qualquer risco técnico do laboratório",
      "Para substituir as regras do provedor de nuvem",
    ],
    correct: 1,
    explanation:
      "A autorização válida estabelece quem pode testar, quais ativos estão incluídos, quando e de que forma. Boa intenção ou acesso a uma conta não substituem esse limite explícito.",
  },
  {
    id: "medium-security-group-ssh",
    difficulty: "medium",
    topic: "Rede e SSH",
    lesson: "8. Acesso remoto com SSH",
    source: "02-cloud-basics/08-communicating-with-cloud-computers-remotely-using-ssh/",
    question: "Por que liberar TCP/22 no Security Group não garante que o SSH funcione?",
    choices: [
      "Porque o Security Group converte a porta 22 em 443",
      "Porque ainda são necessários rota, endereço alcançável e sshd em escuta",
      "Porque o SSH funciona somente dentro da rede local",
      "Porque liberar a porta desativa a autenticação por chave",
    ],
    correct: 1,
    explanation:
      "O Security Group só permite a passagem do tráfego. A conexão ainda depende de roteamento, endereço correto, controles locais e de um processo sshd ativo escutando na porta esperada.",
  },
  {
    id: "medium-private-key",
    difficulty: "medium",
    topic: "Chaves SSH",
    lesson: "8. Acesso remoto com SSH",
    source: "02-cloud-basics/08-communicating-with-cloud-computers-remotely-using-ssh/",
    question: "Qual é o principal risco de uma chave privada SSH ser exposta?",
    choices: [
      "Ela revela automaticamente todos os arquivos do servidor",
      "Ela pode permitir autenticação nos hosts que confiam na chave pública correspondente",
      "Ela altera o endereço IP da instância",
      "Ela impede que o servidor use criptografia",
    ],
    correct: 1,
    explanation:
      "Quem possui a chave privada pode produzir assinaturas válidas para os servidores que autorizaram a chave pública correspondente. Por isso ela não deve ser compartilhada ou publicada.",
  },
  {
    id: "medium-hypervisor",
    difficulty: "medium",
    topic: "Virtualização",
    lesson: "3. O que é computação em nuvem?",
    source: "01-introduction-to-cloud-computing-for-hackers/03-what-is-the-cloud/",
    question: "Como um hipervisor permite várias máquinas virtuais no mesmo servidor físico?",
    choices: [
      "Criando um datacenter diferente para cada máquina",
      "Apresentando recursos virtuais isolados sobre o hardware compartilhado",
      "Removendo a necessidade de processador e memória físicos",
      "Transformando cada aplicação em um endereço IP",
    ],
    correct: 1,
    explanation:
      "O hipervisor abstrai e distribui CPU, memória, disco e rede físicos entre máquinas virtuais isoladas logicamente. O hardware continua real e compartilhado.",
  },
  {
    id: "medium-stop-cost",
    difficulty: "medium",
    topic: "Custos na AWS",
    lesson: "5. Roteiro e laboratório seguro",
    source: "02-cloud-basics/05-introduction-to-cloud-basics/",
    question: "Por que parar uma instância EC2 pode não zerar todos os custos?",
    choices: [
      "Porque a CPU continua executando em velocidade reduzida",
      "Porque recursos associados, como volumes e endereços públicos, podem continuar alocados",
      "Porque instâncias paradas são convertidas em servidores físicos",
      "Porque o Security Group cobra por cada regra ativa",
    ],
    correct: 1,
    explanation:
      "Parar interrompe a computação da instância, mas recursos persistentes ou alocados separadamente podem continuar cobrados. A limpeza deve revisar volumes, endereços e outros recursos do laboratório.",
  },
  {
    id: "medium-ssh-auth",
    difficulty: "medium",
    topic: "Autenticação SSH",
    lesson: "8. Acesso remoto com SSH",
    source: "02-cloud-basics/08-communicating-with-cloud-computers-remotely-using-ssh/",
    question: "Como o SSH comprova a posse da chave privada sem enviá-la ao servidor?",
    choices: [
      "O cliente envia uma cópia temporária da chave",
      "O cliente assina dados da sessão e o servidor verifica com a chave pública",
      "O servidor reconstrói a chave privada a partir da pública",
      "As duas chaves são enviadas como uma senha dupla",
    ],
    correct: 1,
    explanation:
      "O cliente usa a chave privada localmente para assinar dados vinculados à sessão. O servidor valida a assinatura com a chave pública autorizada; a chave privada nunca precisa atravessar a rede.",
  },
  {
    id: "medium-compromise-layers",
    difficulty: "medium",
    topic: "Camadas de comprometimento",
    lesson: "2. Hacking ético, pentest e Red Team",
    source: "01-introduction-to-cloud-computing-for-hackers/02-introduction-to-hacking-using-the-cloud/",
    question: "Qual diferença entre comprometer uma conta, o navegador e o sistema está correta?",
    choices: [
      "São três nomes para o mesmo resultado",
      "Conta dá acesso a um serviço; navegador executa em sandbox; sistema executa com privilégios locais",
      "Comprometer uma conta sempre concede controle administrativo do sistema",
      "Comprometer o navegador elimina automaticamente a política de mesma origem",
    ],
    correct: 1,
    explanation:
      "Cada resultado pertence a uma camada diferente. Passar de uma conta para o navegador ou para o sistema exige condições adicionais e precisa ser comprovado separadamente.",
  },
  {
    id: "medium-phishing-no-bug",
    difficulty: "medium",
    topic: "Engenharia social",
    lesson: "10. Phishing e engenharia social",
    source: "03-phishing/10-introduction-to-phishing/",
    question: "Como o phishing pode funcionar sem explorar uma vulnerabilidade de software?",
    choices: [
      "Ele sempre contém um exploit invisível",
      "Ele influencia uma decisão humana por meio de pretexto, contexto e isca",
      "Ele desativa automaticamente a sandbox do navegador",
      "Ele transforma uma mensagem em código do sistema operacional",
    ],
    correct: 1,
    explanation:
      "Engenharia social atua sobre a interpretação e a decisão da pessoa. O software pode estar funcionando como projetado, enquanto o pretexto induz uma ação insegura.",
  },
  {
    id: "medium-http-flow",
    difficulty: "medium",
    topic: "Fluxo HTTP",
    lesson: "11. Apache, HTTP e exposição web",
    source: "03-phishing/11-file-hosting-and-firewall-settings/",
    question: "Qual sequência representa melhor uma visita HTTP ao Apache na instância?",
    choices: [
      "Navegador → IP do destino → TCP/80 → controles de rede → Apache",
      "Navegador → arquivo local → banco de dados → Apache",
      "Apache → DNS → navegador → Security Group",
      "Navegador → porta física 80 → chave SSH → Apache",
    ],
    correct: 0,
    explanation:
      "O navegador encontra o endereço do destino, abre uma conexão TCP na porta 80, atravessa os controles de rede permitidos e chega ao processo Apache que está escutando.",
  },
  {
    id: "medium-sftp-permission",
    difficulty: "medium",
    topic: "Permissões Linux",
    lesson: "13. Publicando uma página no Apache",
    source: "03-phishing/13-creating-a-fake-login-page-on-the-cloud/",
    question: "Por que o upload falhou mesmo depois de o SFTP conectar corretamente?",
    choices: [
      "Porque o Apache não aceita arquivos HTML",
      "Porque o usuário kali não tinha permissão de escrita no diretório pertencente a root",
      "Porque SFTP permite download, mas nunca upload",
      "Porque o Security Group bloqueava operações no disco",
    ],
    correct: 1,
    explanation:
      "Autenticação e permissão no sistema de arquivos são controles diferentes. A sessão SFTP era válida, mas o usuário kali não podia escrever em um diretório cujo proprietário era root.",
  },
  {
    id: "hard-provider-policy",
    difficulty: "hard",
    topic: "Ética e nuvem",
    lesson: "4. Nuvem em testes autorizados",
    source: "01-introduction-to-cloud-computing-for-hackers/04-why-learn-cloud-computing-as-a-hacker/",
    question: "Um teste autorizado pelo dono do alvo viola a política do provedor de nuvem. O que isso significa?",
    choices: [
      "A autorização do alvo sempre anula a política do provedor",
      "A atividade pode ser bloqueada e a conta suspensa mesmo com autorização do alvo",
      "O provedor passa a responder pelo resultado do teste",
      "Nenhuma regra do provedor se aplica a laboratórios",
    ],
    correct: 1,
    explanation:
      "Autorização sobre o alvo e permissão para usar a infraestrutura são relações diferentes. O teste deve respeitar também os termos e políticas atuais do provedor.",
  },
  {
    id: "hard-ip-and-ssh",
    difficulty: "hard",
    topic: "Rede e identidade",
    lesson: "8. Acesso remoto com SSH",
    source: "02-cloud-basics/08-communicating-with-cloud-computers-remotely-using-ssh/",
    question: "Por que mudar o IPv4 público da instância não invalida a chave privada SSH?",
    choices: [
      "Porque a chave privada contém todos os endereços futuros",
      "Porque a AWS autentica pela região, não pelo endereço",
      "Porque endereço de rede e prova criptográfica de identidade são controles distintos",
      "Porque SSH ignora completamente endereços IP",
    ],
    correct: 2,
    explanation:
      "O IP localiza o servidor na rede; a chave prova a posse de uma credencial. O cliente precisa usar o novo endereço, mas a correspondência entre a chave privada e a pública autorizada continua válida.",
  },
  {
    id: "hard-cloud-evidence",
    difficulty: "hard",
    topic: "Computação em nuvem",
    lesson: "3. O que é computação em nuvem?",
    source: "01-introduction-to-cloud-computing-for-hackers/03-what-is-the-cloud/",
    question: "Uma aplicação está acessível pela Internet. O que isso prova sobre o uso de nuvem?",
    choices: [
      "Prova que ela está na AWS",
      "Prova que ela usa máquinas virtuais",
      "Não prova uso de nuvem; conectividade e modelo de infraestrutura são conceitos distintos",
      "Prova que ela usa escalabilidade automática",
    ],
    correct: 2,
    explanation:
      "Internet descreve conectividade entre redes. Nuvem descreve um modelo de provisão e consumo de recursos. Um serviço pode estar online em infraestrutura própria ou em nuvem.",
  },
  {
    id: "hard-callback",
    difficulty: "hard",
    topic: "Fluxo de rede",
    lesson: "4. Nuvem em testes autorizados",
    source: "01-introduction-to-cloud-computing-for-hackers/04-why-learn-cloud-computing-as-a-hacker/",
    question: "Por que uma conexão iniciada pelo agente do laboratório pode funcionar quando entradas diretas são bloqueadas?",
    choices: [
      "Porque conexões de saída atravessam qualquer firewall",
      "Porque regras de saída podem ser diferentes, embora rota, DNS e destino ainda precisem funcionar",
      "Porque o callback desativa o firewall durante a conexão",
      "Porque conexões iniciadas pelo agente não usam protocolos de rede",
    ],
    correct: 1,
    explanation:
      "Controles podem permitir tráfego iniciado de dentro e bloquear novas conexões de entrada. Isso não é um desvio automático: o agente ainda depende de execução, rota, resolução e destino acessível dentro do escopo autorizado.",
  },
  {
    id: "hard-https-phishing",
    difficulty: "hard",
    topic: "HTTPS e confiança",
    lesson: "10. Phishing e engenharia social",
    source: "03-phishing/10-introduction-to-phishing/",
    question: "Um domínio enganoso apresenta HTTPS válido. O que o certificado realmente confirma?",
    choices: [
      "Que o conteúdo e a organização são legítimos",
      "Que não existe phishing naquela página",
      "Que a conexão é protegida e o certificado corresponde ao domínio exibido",
      "Que o domínio pertence à marca imitada",
    ],
    correct: 2,
    explanation:
      "HTTPS protege a comunicação e autentica o domínio do certificado. Ele não declara que o domínio pertence à organização que a página afirma representar.",
  },
  {
    id: "hard-port-service",
    difficulty: "hard",
    topic: "Camadas de rede",
    lesson: "11. Apache, HTTP e exposição web",
    source: "03-phishing/11-file-hosting-and-firewall-settings/",
    question: "Qual diferença entre liberar TCP/80 e iniciar o Apache?",
    choices: [
      "Nenhuma; são duas formas de executar a mesma ação",
      "A regra permite tráfego; o Apache cria o processo que escuta e responde",
      "Liberar a porta instala e inicia o Apache automaticamente",
      "Iniciar o Apache altera o Security Group da AWS",
    ],
    correct: 1,
    explanation:
      "São camadas independentes. O firewall pode permitir o tráfego sem haver serviço escutando, e o serviço pode estar ativo enquanto a rede bloqueia o acesso externo.",
  },
  {
    id: "hard-static-copy",
    difficulty: "hard",
    topic: "Publicação web",
    lesson: "12. Cópia de páginas e SFTP",
    source: "03-phishing/12-cloning-websites-and-uploading-them-to-the-cloud/",
    question: "Por que copiar HTML, CSS e imagens não reproduz automaticamente um site funcional?",
    choices: [
      "Porque o Apache não consegue servir HTML copiado",
      "Porque a cópia não inclui necessariamente back-end, banco, APIs privadas e autenticação",
      "Porque navegadores removem todas as folhas de estilo ao salvar",
      "Porque SFTP converte páginas em texto simples",
    ],
    correct: 1,
    explanation:
      "A cópia contém apenas recursos recebidos pelo navegador. Lógica de servidor, dados, serviços privados e integrações continuam fora dela, por isso a aparência estática não equivale ao sistema original.",
  },
  {
    id: "hard-permissions",
    difficulty: "hard",
    topic: "Permissões Linux",
    lesson: "13. Publicando uma página no Apache",
    source: "03-phishing/13-creating-a-fake-login-page-on-the-cloud/",
    question: "Em um diretório root:root com permissão drwxr-xr-x, o que o usuário kali pode fazer como “outro”?",
    choices: [
      "Ler e atravessar o diretório, mas não criar arquivos nele",
      "Criar, alterar e remover qualquer arquivo",
      "Alterar o proprietário sem sudo",
      "Somente escrever, sem listar ou atravessar",
    ],
    correct: 0,
    explanation:
      "Os três últimos bits são r-x para outros: leitura e travessia, sem escrita. Como kali não é root nem pertence ao grupo proprietário, não pode criar arquivos nesse diretório.",
  },
  {
    id: "hard-chown",
    difficulty: "hard",
    topic: "Propriedade de arquivos",
    lesson: "13. Publicando uma página no Apache",
    source: "03-phishing/13-creating-a-fake-login-page-on-the-cloud/",
    question: "O que sudo chown kali:kali /var/www/html -R altera diretamente?",
    choices: [
      "As regras TCP/80 do Security Group",
      "O proprietário e o grupo do diretório e de seu conteúdo, recursivamente",
      "O modo de autenticação do SFTP",
      "O processo que escuta na porta 80",
    ],
    correct: 1,
    explanation:
      "chown altera propriedade; kali:kali define usuário e grupo, e -R aplica a mudança recursivamente. O comando não inicia Apache, não abre portas e não muda a autenticação SSH.",
  },
  {
    id: "hard-root-mfa",
    difficulty: "hard",
    topic: "Segurança da conta AWS",
    lesson: "6. Criando e protegendo uma conta AWS",
    source: "02-cloud-basics/06-signing-up-with-aws/",
    question: "Por que proteger o usuário root da AWS com MFA não elimina a necessidade de identidades limitadas no uso diário?",
    choices: [
      "Porque MFA funciona apenas em instâncias EC2",
      "Porque MFA protege o login, enquanto menor privilégio limita o impacto após o acesso",
      "Porque usuários limitados não precisam se autenticar",
      "Porque o root não consegue modificar recursos da conta",
    ],
    correct: 1,
    explanation:
      "MFA reduz o risco de entrada indevida, mas o root continua tendo poder amplo quando autenticado. Usar identidades com apenas as permissões necessárias limita erros e comprometimentos.",
  },
];